### ISSUE TITLE
not working with node 10 and later

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [acrisci/simple-breakpad-server#20] opened 2018-11-06 11:24 UTC
Please add support for latest node js

**Comment by Jimbly** [comment] 2018-11-06 17:33
Looks like the problem is the sqlite3@3 module does not work on Node v10+, however v4 of sqlite3 does, and it doesn't seem like there's any breaking changes between v3 and v4, so installing v4 should probably solve the issue for you:  `npm i --no-save sqlite3@4.0.3`.  I haven't had time to fully test, but if that works for you, it's probably safe for us to just update to that sqlite3 version.

**Comment by tzvetelin-vassilev** [comment] 2018-11-08 14:14
I was not able to integrate this version of sqlite3. I got new errors when try to install it.

**Comment by tzvetelin-vassilev** [comment] 2018-11-09 15:41
4.0.3 not works with node 11, they have such issue, we need to wait little bit to fix that

**Comment by Jimbly** [comment] 2018-11-09 16:07
Since sqlite3 requires native builds, which can be tricky on some platforms, it's probably safest to stick to the stable/LTS (even numbered) Node releases - it should work on Node v10.x, but might not consistently on v11.x.

**Comment by Jimbly** [comment] 2019-09-18 19:55
Fixed in #22.

**Closed by Jimbly** 2019-09-18 19:55 UTC
