### ISSUE TITLE
Not able to analyze any breakpad symbol files

### ISSUE THREAD

**Issue by saumilsdk** [acrisci/simple-breakpad-server#15] opened 2018-03-26 14:37 UTC
I tried posting symbol files from breakpad testdata. It uploads symbol files but when I click on view, it fails. 
Here are the symbol files to try with:
https://github.com/google/breakpad/tree/master/src/processor/testdata/symbols

**Comment by Jimbly** [comment] 2018-03-26 14:50
What do you mean by "analyze any breakpad symbol files"?  Symbol files are not analyzed in anyway way by simple-breakpad-server, they are simply stored on disk for breakpad's minidump_stackwalk tool to read when you view an uploaded dump.  Or is this a duplicate of the issue you just posted where you get a crash when trying to download a previously uploaded symbol file?

**Comment by saumilsdk** [comment] 2018-03-27 04:46
just a simple typo, has been fixed in #16.

**Closed** 2018-03-27 04:47 UTC
